apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoheaders
spec:
  selector:
    matchLabels:
      app: echoheaders
  replicas: 1
  template:
    metadata:
      labels:
        app: echoheaders
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.4
        name: echoheaders
        ports:
        - containerPort: 8080
